---
title: "JFF"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(keras)
library(tidyr)
library(tensorflow)
library(caret)
library(readr)

#install_tensorflow()
```

#Full Join of Data
```{r}
df <- read_csv("C:\\Users\\kateb\\Downloads\\111.csv")
```

```{r}
index <- createDataPartition(df$childcare, p=0.7, list=FALSE)
final.training <- df[index,]
final.test <- df[-index,]
# write_csv(final.training, "C:\\Users\\kateb\\Downloads\\finaltraining.csv")
# write_csv(final.test, "C:\\Users\\kateb\\Downloads\\finaltesting.csv")
```

```{r}
X_train <- final.training %>%
  dplyr::select(-childcare) %>%
  scale()

y_train <- to_categorical(final.training$childcare)
```

```{r}
X_test <- final.test %>% 
  dplyr::select(-childcare) %>% 
  scale()

y_test <- to_categorical(final.test$childcare)
```

```{r}
model <- keras_model_sequential() 

model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = ncol(X_train)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 2, activation = 'sigmoid')

history <- model %>% compile(
  loss = 'binary_crossentropy',
  optimizer = 'adam',
  metrics = c('accuracy')
)

model %>% fit(
  X_train, y_train, 
  epochs = 50, 
  batch_size = 10,
  validation_split = 0.3
)
```

```{r}
summary(model)
```

```{r}
model %>% evaluate(X_test, y_test)
```

```{r}
#Making predictions on the testing dataset that was exempt from the training process
predictions <- model %>% predict_classes(X_test)

#Creating a confusion matrix to observe the model's performance
table(factor(predictions, levels=min(final.test$childcare):max(final.test$childcare)),factor(final.test$childcare, levels=min(final.test$childcare):max(final.test$childcare)))
```


Based on the above confusion matrix, no false positives or negatives were predicted onto the test dataset, so the accuracy of our training set is 100%.

```{r}
save_model_hdf5(model, "rkerasmodel.h5")
model <- load_model_hdf5("rkerasmodel.h5")
```